#ifndef GDATAQTNESSGOAUTH_GLOBAL_H
#define GDATAQTNESSGOAUTH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GDATAQTNESSGOAUTH_LIBRARY)
#  define GDATAQTNESSGOAUTHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GDATAQTNESSGOAUTHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GDATAQTNESSGOAUTH_GLOBAL_H
