#ifndef GDATAQTNESSGOAUTH2_GLOBAL_H
#define GDATAQTNESSGOAUTH2_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GDATAQTNESSGOAUTH2_LIBRARY)
#  define GDATAQTNESSGOAUTH2SHARED_EXPORT Q_DECL_EXPORT
#else
#  define GDATAQTNESSGOAUTH2SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GDATAQTNESSGOAUTH2_GLOBAL_H
